### ISSUE TITLE
Health drain modifier

### ISSUE THREAD

**Issue by SanicBTW** [SanicBTW/FNF-PE-0.3.2h#3]
If there is no health drain amount then it won't work, I was using null as the check but when compiling it gave me errors (it doesn't happen on html5) so I changed to < 0 but it seems to not be working

**Comment by SanicBTW** [comment]
Fixed

**Comment by LEVIXDDLMAO** [comment]
will this be html or?

**Comment by SanicBTW** [comment]
bruh i already showed you the progress on the server and stop asking please if its html or not, im literally always talking about each platform 😭

**Comment by SanicBTW** [comment]
also modifiers are cancelled to keep the engine vanilla psych

**Comment by LEVIXDDLMAO** [comment]
You should know i cant remeber things

**Comment by SanicBTW** [comment]
whatever
