### ISSUE TITLE
Random Question

### ISSUE THREAD

**Issue by Ty1991twitter** [SanicBTW/FNF-PE-0.3.2h#4]
Not really an issue but could I use this as a base for my FNF engine?

**Comment by SanicBTW** [comment]
Yeah go on, though you might want to use a newer version due to improvements and more stuff, this has android support and some funky file system support, you are free to fork it or use it for whatever you want, if you need help you can add me on discord sanco#8424

**Comment by Ty1991twitter** [comment]
aight thanks

**Comment by SanicBTW** [comment]
alright then hmu on discord or here if you need anything else!
