### ISSUE TITLE
Hit sound issue

### ISSUE THREAD

**Issue by SanicBTW** [SanicBTW/FNF-PE-0.3.2h#5]
When playing hitsound fps decrease, I don't see this happening on PE 0.5.2h, I will take a look into it soon

**Comment by LEVIXDDLMAO** [comment]
Homie for your flight or fight port you need to add a ester egg for me :D about me

**Comment by SanicBTW** [comment]
why tho

**Comment by SanicBTW** [comment]
and what would i add for the easter egg

**Comment by LEVIXDDLMAO** [comment]
> why tho

You dont have to its just an idea

**Comment by LEVIXDDLMAO** [comment]
> and what would i add for the easter egg

My little happy face'
:D

**Comment by SanicBTW** [comment]
ehhhhhhh alright ill look into it once i finish working on the big update or smth

**Comment by LEVIXDDLMAO** [comment]
kk :D

**Comment by LEVIXDDLMAO** [comment]
heyyyyy how do i add the memory thing? ( im working on indie cross PE sc My take tho ) I wanna get it too look like indie cross

**Comment by SanicBTW** [comment]
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh dunno but you can use the MemoryCounter thing from this repo and add it to yours, to add to the game go to Main.hx and declare a new variable called memoryVar:MemoryCounter; or wahtever you want to call it, then below adding fpsVar create a new memorycounter


it should be something like this =

```	
public static var memoryVar:MemoryCounter;
```

```
		fpsVar = new FPS(10, 8, 0xFFFFFF);
		addChild(fpsVar);
		if(fpsVar != null) {
			fpsVar.visible = ClientPrefs.showFPS;
		}

		memoryVar = new MemoryCounter(10, 20);
		addChild(memoryVar);
		if(memoryVar != null){
			memoryVar.visible = ClientPrefs.showMemory;
		}
```

**Comment by LEVIXDDLMAO** [comment]
ah okay! thank you!

**Comment by SanicBTW** [comment]
yw bro

**Comment by LEVIXDDLMAO** [comment]
:D
